{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4fdadb3-d183-4b1b-9610-df49da3e71ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "# List of file paths to reset\n",
    "file_paths = [\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Predictions\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\PKL\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Reference Data_Update.xlsx\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Reference Data_Dropped.xlsx\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Single_Class_Groups.xlsx\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Model_Info.xlsx\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Unprocessed_Input_Data.xlsx\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Grouped_Input_Data.csv\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\merged_output.xlsx\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\updated_merged_output.xlsx\",\n",
    "    r\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Block-2.log\"\n",
    "]\n",
    "\n",
    "def reset_files(file_paths):\n",
    "    for file_path in file_paths:\n",
    "        try:\n",
    "            # Check if the path is a directory\n",
    "            if os.path.isdir(file_path):\n",
    "                # Clear the directory by removing all files within it\n",
    "                for filename in os.listdir(file_path):\n",
    "                    file_to_remove = os.path.join(file_path, filename)\n",
    "                    if os.path.isfile(file_to_remove):\n",
    "                        os.remove(file_to_remove)\n",
    "                print(f\"Cleared directory: {file_path}\")\n",
    "            else:\n",
    "                # Clear the file by opening it in write mode and then closing it\n",
    "                with open(file_path, 'w') as file:\n",
    "                    pass\n",
    "                print(f\"Cleared file: {file_path}\")\n",
    "        except Exception as e:\n",
    "            print(f\"Error resetting {file_path}: {e}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    reset_files(file_paths)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b99b2b4c-e312-4c19-9ac1-b6481b3ba4bd",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Block-1:- Imports and Preprocessing\n",
    "import pandas as pd\n",
    "import re\n",
    "from sys import exit\n",
    "\n",
    "# Function to extract the first part of the description based on specific rules\n",
    "def extract_first_word(description):\n",
    "    if isinstance(description, str):\n",
    "        # Check for semicolon, comma, or dash and extract accordingly\n",
    "        if ';' in description:\n",
    "            first_part = description.split(';')[0]\n",
    "        elif ',' in description:\n",
    "            first_part = description.split(',')[0]\n",
    "        elif '-' in description:\n",
    "            first_part = description.split('-')[0]\n",
    "        else:\n",
    "            first_part = description.split()[0]\n",
    "        \n",
    "        # Extract words and apply transformations\n",
    "        words = re.findall(r'\\b[a-zA-Z-]+\\b', first_part)\n",
    "        \n",
    "        if ';' in description:\n",
    "            return ' '.join(words[:2]).upper() if len(words) >= 2 else ' '.join(words).upper()\n",
    "        elif ',' in description or '-' in description:\n",
    "            return words[0].upper() if words else ''\n",
    "        else:\n",
    "            first_part = re.sub(r'[^\\w\\s-]', '', first_part)  # Remove punctuation except dash and spaces\n",
    "            first_part = re.sub(r'\\d', '', first_part)  # Remove numbers\n",
    "            return first_part.strip().upper()  # Strip leading/trailing spaces and convert to uppercase\n",
    "    \n",
    "    return ''\n",
    "\n",
    "# Function to extract the first segments of Product_Taxonomy_Node\n",
    "def extract_partial_taxonomy(node):\n",
    "    segment_mapping = {\n",
    "        r'Parts and Supplies\\Coil': 2,\n",
    "        r'Parts and Supplies\\Compressor': 2,\n",
    "        r'Parts and Supplies\\Controls, Sensors & Valves': 3,\n",
    "        r'Parts and Supplies\\Equipment Accessories': 2,\n",
    "        r'Parts and Supplies\\Filtration & Purification': 2,\n",
    "        r'Parts and Supplies\\Indoor Air Quality (IAQ) and Ventilation': 3,\n",
    "        r'Parts and Supplies\\Motors': 2,\n",
    "        r'Parts and Supplies\\Refrigerant & Oil': 3,\n",
    "        r'Parts and Supplies\\Rental Units, Parts & Accessories': 2,\n",
    "        r'Parts and Supplies\\Service Parts & Supplies': 3\n",
    "    }\n",
    "        \n",
    "    default_segments = 2\n",
    "    num_segments = default_segments\n",
    "    for key, segments in segment_mapping.items():\n",
    "        if node.startswith(key):\n",
    "            num_segments = segments\n",
    "            break\n",
    "    segments = node.split('\\\\')\n",
    "    partial_segments = segments[:num_segments]\n",
    "    return '\\\\'.join(partial_segments)\n",
    "\n",
    "# Read the Excel file\n",
    "input_file = 'Reference data-1.xlsx'\n",
    "try:\n",
    "    df = pd.read_excel(input_file, sheet_name='Query1')\n",
    "    print(f\"Data has been read from {input_file}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error reading data from {input_file}: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Ensure columns are treated as strings\n",
    "df['Item_Number'] = df['Item_Number'].astype(str)\n",
    "df['Item_Description'] = df['Item_Description'].astype(str)\n",
    "df['Product_Taxonomy_Node'] = df['Product_Taxonomy_Node'].astype(str)\n",
    "\n",
    "print(f\"Initial data count: {len(df)}\")\n",
    "\n",
    "# Remove duplicate items based on 'Item_Number'\n",
    "df = df.drop_duplicates(subset=['Item_Number'])\n",
    "print(f\"Data count after removing duplicates: {len(df)}\")\n",
    "\n",
    "# Convert the entire Item_Description to uppercase and remove extra spaces\n",
    "df['Item_Description'] = df['Item_Description'].str.upper().str.strip()\n",
    "\n",
    "# Apply the functions to each row\n",
    "print(\"Extracting first words...\")\n",
    "df['First_Word'] = df['Item_Description'].apply(extract_first_word)\n",
    "\n",
    "# Remove leading dashes and spaces from the First_Word column\n",
    "df['First_Word'] = df['First_Word'].str.lstrip('- ').str.strip()\n",
    "\n",
    "# Identify rows with single alphabet First_Word\n",
    "single_alphabet_df = df[df['First_Word'].str.len() <= 2]\n",
    "\n",
    "# Identify rows where First_Word could not be extracted\n",
    "no_first_word_df = df[df['First_Word'] == '']\n",
    "\n",
    "# Combine the two DataFrames to get all unprocessed rows\n",
    "unprocessed_df = pd.concat([single_alphabet_df, no_first_word_df]).drop_duplicates()\n",
    "\n",
    "# Drop rows where First_Word is a single alphabet or could not be extracted\n",
    "df = df[df['First_Word'].str.len() > 2]\n",
    "df = df[df['First_Word'] != '']\n",
    "print(f\"Data count after dropping single alphabet and empty First_Word: {len(df)}\")\n",
    "\n",
    "# Apply the extract_partial_taxonomy function\n",
    "print(\"Extracting partial taxonomy nodes...\")\n",
    "df['Partial_Taxonomy_Node'] = df['Product_Taxonomy_Node'].apply(extract_partial_taxonomy)\n",
    "\n",
    "# Group by First_Word and Partial_Taxonomy_Node to get the count\n",
    "count_df = df.groupby(['First_Word', 'Partial_Taxonomy_Node']).size().reset_index(name='Count')\n",
    "\n",
    "# Remove duplicates in the Reference sheet based on 'Item_Number'\n",
    "df = df.drop_duplicates(subset=['Item_Number'])\n",
    "\n",
    "# Save the detailed DataFrame and the count DataFrame to an Excel file with two sheets\n",
    "output_file = 'Reference Data_Update.xlsx'\n",
    "try:\n",
    "    with pd.ExcelWriter(output_file) as writer:\n",
    "        df[['Item_Number', 'Item_Description', 'First_Word', 'Product_Taxonomy_Node', 'Partial_Taxonomy_Node']].to_excel(writer, sheet_name='Reference', index=False)\n",
    "        count_df.to_excel(writer, sheet_name='Count', index=False)\n",
    "    print(f\"Data has been saved to {output_file}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error saving data to {output_file}: {e}\")\n",
    "\n",
    "# Save the unprocessed DataFrame to a new Excel file\n",
    "output_file_dropped = 'Reference Data_Dropped.xlsx'\n",
    "try:\n",
    "    with pd.ExcelWriter(output_file_dropped) as writer:\n",
    "        unprocessed_df.to_excel(writer, sheet_name='Unprocessed', index=False)\n",
    "    print(f\"Dropped data has been saved to {output_file_dropped}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error saving dropped data to {output_file_dropped}: {e}\")\n",
    "\n",
    "print(\"Processing completed.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b47047ca-69b7-446d-aff2-c8d8ae1e3d27",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Block-2:- Model Training\n",
    "\n",
    "import pandas as pd\n",
    "import re\n",
    "import os\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import joblib\n",
    "from tqdm import tqdm\n",
    "import logging\n",
    "from concurrent.futures import ThreadPoolExecutor, as_completed\n",
    "\n",
    "# Configure logging to file only\n",
    "logger = logging.getLogger()\n",
    "logger.setLevel(logging.INFO)\n",
    "file_handler = logging.FileHandler('Block-2.log', mode='w')\n",
    "formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')\n",
    "file_handler.setFormatter(formatter)\n",
    "logger.addHandler(file_handler)\n",
    "\n",
    "# Read the Excel file\n",
    "input_file = 'Reference Data_Update.xlsx'  # Replace with your input file name\n",
    "try:\n",
    "    df = pd.read_excel(input_file, sheet_name='Reference')\n",
    "    logger.info(f\"Data has been read from {input_file}\")\n",
    "except Exception as e:\n",
    "    logger.error(f\"Error reading data from {input_file}: {e}\")\n",
    "    exit()\n",
    "logger.info(f\"Initial data count: {len(df)}\")\n",
    "\n",
    "# Check for duplicates based on Item_Number\n",
    "duplicates = df[df.duplicated(subset='Item_Number', keep=False)]\n",
    "if not duplicates.empty:\n",
    "    logger.warning(f\"Found {len(duplicates)} duplicate rows based on Item_Number\")\n",
    "    duplicates.to_excel('duplicates.xlsx', index=False)\n",
    "    logger.info(\"Duplicate rows have been saved to duplicates.xlsx\")\n",
    "\n",
    "# Optionally, remove duplicates\n",
    "df = df.drop_duplicates(subset='Item_Number')\n",
    "logger.info(f\"Data count after removing duplicates: {len(df)}\")\n",
    "\n",
    "# Group by Partial_Taxonomy_Node\n",
    "grouped = df.groupby('Partial_Taxonomy_Node')\n",
    "logger.info(f\"Number of groups formed: {len(grouped)}\")\n",
    "\n",
    "# Function to sanitize filenames\n",
    "def sanitize_filename(name):\n",
    "    \"\"\"Sanitize the filename by replacing invalid characters with underscores.\"\"\"\n",
    "    return re.sub(r'[\\\\/*?:\"<>|]', '_', name)\n",
    "\n",
    "# Function to train and save model for a group\n",
    "def train_and_save_model(name, group):\n",
    "    \"\"\"Train and save the model for a given group.\"\"\"\n",
    "    try:\n",
    "        # Convert Item_Description to uppercase and remove extra spaces\n",
    "        group = group.copy()\n",
    "        group['Item_Description'] = group['Item_Description'].str.upper().str.strip()\n",
    "        \n",
    "        # Use only Item_Description for training\n",
    "        X = group['Item_Description']\n",
    "        y = group['Product_Taxonomy_Node']\n",
    "        \n",
    "        # Log group details\n",
    "        logger.info(f\"Processing group '{name}' with {len(group)} samples and {len(y.unique())} unique classes\")\n",
    "        \n",
    "        # Check if there is more than one unique class\n",
    "        if len(y.unique()) > 1:\n",
    "            # Encode labels\n",
    "            le = LabelEncoder()\n",
    "            y_encoded = le.fit_transform(y)\n",
    "            \n",
    "            # Create a pipeline with TF-IDF Vectorizer and SVM\n",
    "            model = make_pipeline(TfidfVectorizer(), SVC(kernel='linear', probability=True))\n",
    "            \n",
    "            # Train the model\n",
    "            model.fit(X, y_encoded)\n",
    "            \n",
    "            # Save the model and the label encoder\n",
    "            partial_taxonomy_node = name  # Extract Partial_Taxonomy_Node\n",
    "            model_filename = sanitize_filename(partial_taxonomy_node) + '.pkl'\n",
    "            le_filename = sanitize_filename(partial_taxonomy_node) + '_le.pkl'\n",
    "            model_path = os.path.join('PKL', model_filename)\n",
    "            le_path = os.path.join('PKL', le_filename)\n",
    "            \n",
    "            # Ensure the directory exists\n",
    "            os.makedirs(os.path.dirname(model_path), exist_ok=True)\n",
    "            joblib.dump(model, model_path)\n",
    "            joblib.dump(le, le_path)\n",
    "            \n",
    "            logger.info(f\"Model and LabelEncoder saved as {model_path} and {le_path}\")\n",
    "            return {'Partial_Taxonomy_Node': partial_taxonomy_node, 'Model_Filename': model_path, 'LabelEncoder_Filename': le_path}\n",
    "        else:\n",
    "            logger.info(f\"Skipping group '{name}' because it has only one unique class.\")\n",
    "            return {'Partial_Taxonomy_Node': name, 'Reason': 'Only one unique class'}\n",
    "    except Exception as e:\n",
    "        logger.error(f\"Error processing group '{name}': {e}\")\n",
    "        return {'Partial_Taxonomy_Node': name, 'Reason': str(e)}\n",
    "\n",
    "# List to store model information and groups with less than one unique class\n",
    "model_info = []\n",
    "single_class_groups = []\n",
    "\n",
    "# Use ThreadPoolExecutor for parallel processing\n",
    "logger.info(\"Starting model training...\")\n",
    "with ThreadPoolExecutor() as executor:\n",
    "    futures = [executor.submit(train_and_save_model, name, group.copy()) for name, group in grouped]\n",
    "    for future in tqdm(as_completed(futures), desc=\"Processing groups\", total=len(grouped)):\n",
    "        result = future.result()\n",
    "        if result:\n",
    "            if 'Model_Filename' in result:\n",
    "                model_info.append(result)\n",
    "            else:\n",
    "                single_class_groups.append(result)\n",
    "logger.info(\"Model training completed.\")\n",
    "\n",
    "# Create a DataFrame from the model information\n",
    "model_info_df = pd.DataFrame(model_info)\n",
    "\n",
    "# Check DataFrame columns\n",
    "expected_columns = ['Partial_Taxonomy_Node', 'Model_Filename', 'LabelEncoder_Filename']\n",
    "if all(column in model_info_df.columns for column in expected_columns):\n",
    "    logger.info(\"Model information DataFrame has the correct columns.\")\n",
    "else:\n",
    "    logger.error(\"Model information DataFrame is missing some columns.\")\n",
    "\n",
    "# Log DataFrame head\n",
    "logger.info(f\"Model information DataFrame head:\\n{model_info_df.head()}\")\n",
    "\n",
    "# Save the DataFrame to an Excel file\n",
    "output_file = 'Model_Info.xlsx'\n",
    "try:\n",
    "    model_info_df.to_excel(output_file, index=False)\n",
    "    logger.info(f\"Model information saved to {output_file}\")\n",
    "except Exception as e:\n",
    "    logger.error(f\"Error saving model information to {output_file}: {e}\")\n",
    "\n",
    "# Save the groups with less than one unique class to an Excel file\n",
    "single_class_df = pd.DataFrame(single_class_groups)\n",
    "single_class_output_file = 'Single_Class_Groups.xlsx'\n",
    "try:\n",
    "    single_class_df.to_excel(single_class_output_file, index=False)\n",
    "    logger.info(f\"Groups with less than one unique class saved to {single_class_output_file}\")\n",
    "except Exception as e:\n",
    "    logger.error(f\"Error saving single class groups to {single_class_output_file}: {e}\")\n",
    "\n",
    "logger.info(\"All models have been trained and saved.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9e47956-247a-41cd-992f-f64adbd28fe3",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Block-3 Predication\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import os\n",
    "import re\n",
    "import logging\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from tqdm import tqdm\n",
    "from datetime import datetime\n",
    "\n",
    "# Configure logging\n",
    "logging.basicConfig(filename='Block-3.log', level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')\n",
    "\n",
    "# Function to extract the first part of the description based on specific rules\n",
    "def extract_first_word(description):\n",
    "    if isinstance(description, str):\n",
    "        # Check for semicolon, comma, or dash and extract accordingly\n",
    "        if ';' in description:\n",
    "            first_part = description.split(';')[0]\n",
    "        elif ',' in description:\n",
    "            first_part = description.split(',')[0]\n",
    "        elif '-' in description:\n",
    "            first_part = description.split('-')[0]\n",
    "        else:\n",
    "            first_part = description.split()[0]\n",
    "        \n",
    "        # Extract words and apply transformations\n",
    "        words = re.findall(r'\\b[a-zA-Z-]+\\b', first_part)\n",
    "        \n",
    "        if ';' in description:\n",
    "            return ' '.join(words[:2]).upper() if len(words) >= 2 else ' '.join(words).upper()\n",
    "        elif ',' in description or '-' in description:\n",
    "            return words[0].upper() if words else ''\n",
    "        else:\n",
    "            first_part = re.sub(r'[^\\w\\s-]', '', first_part)  # Remove punctuation except dash and spaces\n",
    "            first_part = re.sub(r'\\d', '', first_part)  # Remove numbers\n",
    "            return first_part.strip().upper()  # Strip leading/trailing spaces and convert to uppercase\n",
    "    return ''\n",
    "\n",
    "# Function to sanitize filenames\n",
    "def sanitize_filename(name):\n",
    "    \"\"\"Sanitize the filename by replacing invalid characters with underscores.\"\"\"\n",
    "    return re.sub(r'[\\\\/*?:\"<>|]', '_', name)\n",
    "\n",
    "# Function to load the model and label encoder\n",
    "def load_model_and_encoder(model_info_df, partial_taxonomy_node):\n",
    "    model_info = model_info_df[model_info_df['Partial_Taxonomy_Node'] == partial_taxonomy_node]\n",
    "    if not model_info.empty:\n",
    "        model_path = model_info['Model_Filename'].values[0]\n",
    "        le_path = model_info['LabelEncoder_Filename'].values[0]\n",
    "        if os.path.exists(model_path) and os.path.exists(le_path):\n",
    "            model = joblib.load(model_path)\n",
    "            le = joblib.load(le_path)\n",
    "            return model, le\n",
    "    return None, None\n",
    "\n",
    "print(\"Imports and Utility Functions Completed.\")\n",
    "\n",
    "# Part 2: Reading and Preprocessing Data\n",
    "print(\"Reading and Preprocessing Data...\")\n",
    "\n",
    "# Read the input data file\n",
    "input_data_file = r\"C:\\Users\\u113784\\OneDrive - Trane Technologies\\Documents\\Python Code\\SVM\\SVM-7\\Input File.xlsx\"  # Replace with your input data file name\n",
    "try:\n",
    "    input_df = pd.read_excel(input_data_file, usecols=['Item_Number', 'Item_Description'])\n",
    "    logging.info(\"Input data read successfully.\")\n",
    "    print(f\"Input data read successfully from {input_data_file}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error reading data from {input_data_file}: {e}\")\n",
    "    print(f\"Error reading data from {input_data_file}: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Ensure columns are treated as strings\n",
    "input_df['Item_Number'] = input_df['Item_Number'].astype(str)\n",
    "input_df['Item_Description'] = input_df['Item_Description'].astype(str).str.upper().str.strip()\n",
    "\n",
    "# Extract the first word from the item descriptions\n",
    "input_df['First_Word'] = input_df['Item_Description'].apply(extract_first_word)\n",
    "\n",
    "# Read the reference data file from the Reference and Count sheets of Reference Data_Update.xlsx\n",
    "reference_file = 'Reference Data_Update.xlsx'\n",
    "try:\n",
    "    reference_df = pd.read_excel(reference_file, sheet_name='Reference')\n",
    "    count_df = pd.read_excel(reference_file, sheet_name='Count', usecols=['First_Word', 'Partial_Taxonomy_Node', 'Count'])\n",
    "    logging.info(\"Reference data read successfully.\")\n",
    "    print(f\"Reference data read successfully from {reference_file}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error reading data from {reference_file}: {e}\")\n",
    "    print(f\"Error reading data from {reference_file}: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Merge the input data with the count data to get Partial_Taxonomy_Node and Count\n",
    "try:\n",
    "    merged_df = pd.merge(input_df, count_df, on='First_Word', how='left')\n",
    "    logging.info(\"Data merged successfully.\")\n",
    "    print(\"Data merged successfully.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error merging data: {e}\")\n",
    "    print(f\"Error merging data: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Save the unprocessed input data with the specified columns to a new file\n",
    "unprocessed_data_file = 'Unprocessed_Input_Data.xlsx'\n",
    "unprocessed_df = merged_df[['Item_Number', 'Item_Description', 'First_Word', 'Partial_Taxonomy_Node']]\n",
    "try:\n",
    "    unprocessed_df.to_excel(unprocessed_data_file, index=False)\n",
    "    logging.info(f\"Unprocessed input data saved successfully to {unprocessed_data_file}.\")\n",
    "    print(f\"Unprocessed input data saved successfully to {unprocessed_data_file}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error saving unprocessed input data to {unprocessed_data_file}: {e}\")\n",
    "    print(f\"Error saving unprocessed input data to {unprocessed_data_file}: {e}\")\n",
    "\n",
    "# Group the input data item numbers based on the Partial_Taxonomy_Node and Count\n",
    "try:\n",
    "    grouped_df = merged_df.groupby(['Item_Number', 'Item_Description', 'First_Word', 'Partial_Taxonomy_Node', 'Count']).size().reset_index(name='Group_Count')\n",
    "    logging.info(\"Data grouped successfully.\")\n",
    "    print(\"Data grouped successfully.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error grouping data: {e}\")\n",
    "    print(f\"Error grouping data: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Drop the Group_Count column\n",
    "grouped_df = grouped_df.drop(columns=['Group_Count'])\n",
    "\n",
    "# Save the grouped data to a CSV file\n",
    "grouped_output_file = 'Grouped_Input_Data.csv'\n",
    "try:\n",
    "    grouped_df.to_csv(grouped_output_file, index=False)\n",
    "    logging.info(\"Grouped data saved successfully.\")\n",
    "    print(f\"Grouped data saved successfully to {grouped_output_file}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error saving grouped data to {grouped_output_file}: {e}\")\n",
    "    print(f\"Error saving grouped data to {grouped_output_file}: {e}\")\n",
    "\n",
    "# Part 3: Prediction\n",
    "print(\"Starting Prediction...\")\n",
    "\n",
    "# File paths\n",
    "model_info_file = 'Model_Info.xlsx'\n",
    "grouped_input_data_file = 'Grouped_Input_Data.csv'\n",
    "\n",
    "# Read the grouped input data file with specified dtypes\n",
    "try:\n",
    "    dtype_spec = {\n",
    "        'Item_Number': str,  # Assuming Item_Number should be a string\n",
    "        'Item_Description': str,\n",
    "        'First_Word': str,\n",
    "        'Partial_Taxonomy_Node': str,\n",
    "        'Count': int \n",
    "    }\n",
    "    grouped_df = pd.read_csv(grouped_input_data_file, dtype=dtype_spec)\n",
    "    logging.info(\"Grouped input data read successfully.\")\n",
    "    print(f\"Grouped input data read successfully from {grouped_input_data_file}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error reading grouped input data from {grouped_input_data_file}: {e}\")\n",
    "    print(f\"Error reading grouped input data from {grouped_input_data_file}: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Read the model info file\n",
    "try:\n",
    "    model_info_df = pd.read_excel(model_info_file)\n",
    "    logging.info(\"Model info read successfully.\")\n",
    "    print(f\"Model info read successfully from {model_info_file}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error reading model info from {model_info_file}: {e}\")\n",
    "    print(f\"Error reading model info from {model_info_file}: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Predict the Product_Taxonomy_Node for each group\n",
    "predictions = []\n",
    "missing_partial_taxonomy_node = []\n",
    "logging.info(\"Prediction in progress...\")\n",
    "print(\"Prediction in progress...\")\n",
    "\n",
    "# Add tqdm progress bar to the loop\n",
    "for partial_taxonomy_node, group in tqdm(grouped_df.groupby('Partial_Taxonomy_Node'), desc=\"Predicting\", unit=\"group\"):\n",
    "    print(f\"Processing group: {partial_taxonomy_node} with {len(group)} items\")\n",
    "    \n",
    "    # Skip prediction for NULL or blank Partial_Taxonomy_Node or Item_Description\n",
    "    if pd.isnull(partial_taxonomy_node) or partial_taxonomy_node.strip() == '':\n",
    "        missing_partial_taxonomy_node.append(group)\n",
    "        continue\n",
    "    \n",
    "    if group['Item_Description'].isnull().any() or group['Item_Description'].str.strip().eq('').any():\n",
    "        missing_partial_taxonomy_node.append(group)\n",
    "        continue\n",
    "    \n",
    "    model, le = load_model_and_encoder(model_info_df, partial_taxonomy_node)\n",
    "    if model and le:\n",
    "        X = group['Item_Description']\n",
    "        try:\n",
    "            y_pred_encoded = model.predict(X)\n",
    "            y_pred = le.inverse_transform(y_pred_encoded)\n",
    "            y_prob = model.predict_proba(X)\n",
    "            confidence = y_prob.max(axis=1)\n",
    "            group['Predicted_Product_Taxonomy_Node'] = y_pred\n",
    "            group['Confidence_Level'] = confidence\n",
    "            predictions.append(group)\n",
    "        except Exception as e:\n",
    "            logging.error(f\"Error during prediction for {partial_taxonomy_node}: {e}\")\n",
    "    else:\n",
    "        logging.warning(f\"Model or LabelEncoder not found for {partial_taxonomy_node}\")\n",
    "\n",
    "# Part 4: Saving Predictions\n",
    "print(\"Saving Predictions...\")\n",
    "\n",
    "# Combine all predictions into a single DataFrame\n",
    "if predictions:\n",
    "    predictions_df = pd.concat(predictions, ignore_index=True)\n",
    "    # Create the Predictions folder if it doesn't exist\n",
    "    predictions_folder = 'Predictions'\n",
    "    os.makedirs(predictions_folder, exist_ok=True)\n",
    "    # Save the predictions to separate Excel files based on Partial_Taxonomy_Node\n",
    "    for partial_taxonomy_node, group in predictions_df.groupby('Partial_Taxonomy_Node'):\n",
    "        output_file = os.path.join(predictions_folder, f'Predictions_{sanitize_filename(partial_taxonomy_node)}.xlsx')\n",
    "        try:\n",
    "            group.to_excel(output_file, index=False)\n",
    "            logging.info(f\"Predictions for {partial_taxonomy_node} saved successfully to {output_file}.\")\n",
    "            print(f\"Predictions for {partial_taxonomy_node} saved successfully to {output_file}.\")\n",
    "        except Exception as e:\n",
    "            logging.error(f\"Error saving predictions for {partial_taxonomy_node} to {output_file}: {e}\")\n",
    "            print(f\"Error saving predictions for {partial_taxonomy_node} to {output_file}: {e}\")\n",
    "\n",
    "logging.info(\"Prediction processing completed.\")\n",
    "print(\"Prediction processing completed.\")\n",
    "\n",
    "# Part 5: Merging and Selecting Best Predictions\n",
    "print(\"Merging and Selecting Best Predictions...\")\n",
    "\n",
    "# Define the folder containing the Excel files\n",
    "folder_path = 'Predictions'\n",
    "\n",
    "# List to hold dataframes\n",
    "dataframes = []\n",
    "\n",
    "# Loop through all files in the folder\n",
    "for filename in os.listdir(folder_path):\n",
    "    if filename.endswith('.xlsx') or filename.endswith('.xls'):\n",
    "        file_path = os.path.join(folder_path, filename)\n",
    "        # Read the Excel file\n",
    "        df = pd.read_excel(file_path)\n",
    "        # Append the dataframe to the list\n",
    "        dataframes.append(df)\n",
    "\n",
    "# Concatenate all dataframes\n",
    "merged_df = pd.concat(dataframes, ignore_index=True)\n",
    "\n",
    "# Save the merged dataframe to a new Excel file\n",
    "merged_output_file = 'merged_output.xlsx'\n",
    "merged_df.to_excel(merged_output_file, index=False)\n",
    "print(f\"All files have been merged successfully into {merged_output_file}\")\n",
    "\n",
    "# Read the Excel file\n",
    "file_path = 'merged_output.xlsx'\n",
    "df = pd.read_excel(file_path)\n",
    "\n",
    "# Ensure the column names are correct\n",
    "df.columns = ['Item_Number', 'Item_Description', 'First_Word', 'Partial_Taxonomy_Node', 'Count', 'Predicted_Product_Taxonomy_Node', 'Confidence_Level']\n",
    "\n",
    "# Group by Item_Number and calculate the sum of Count\n",
    "sum_count = df.groupby('Item_Number')['Count'].transform('sum')\n",
    "\n",
    "# Calculate Confidence_Percentage as (Count / Sum of Count) * Confidence_Level * 100\n",
    "df['Confidence_Percentage'] = (df['Count'] / sum_count) * df['Confidence_Level'] * 100\n",
    "\n",
    "# Calculate the max of Confidence_Percentage for each Item_Number\n",
    "max_confidence_percentage = df.groupby('Item_Number')['Confidence_Percentage'].transform('max')\n",
    "\n",
    "# Add the new columns to the DataFrame\n",
    "df['Sum_Count'] = sum_count\n",
    "df['Max_Confidence_Percentage'] = max_confidence_percentage\n",
    "\n",
    "# Sort by Item_Number (ascending) and Confidence_Percentage (descending)\n",
    "df = df.sort_values(by=['Item_Number', 'Confidence_Percentage'], ascending=[True, False])\n",
    "\n",
    "# Reorder columns if necessary\n",
    "df = df[['Item_Number', 'Item_Description', 'First_Word', 'Partial_Taxonomy_Node', 'Count', 'Predicted_Product_Taxonomy_Node', 'Confidence_Level', 'Sum_Count', 'Confidence_Percentage', 'Max_Confidence_Percentage']]\n",
    "\n",
    "# Write the updated DataFrame back to an Excel file\n",
    "output_file_path = 'updated_merged_output.xlsx'\n",
    "df.to_excel(output_file_path, index=False)\n",
    "\n",
    "# Get the rows with the highest Confidence_Percentage for each Item_Number\n",
    "top_predictions = df.loc[df.groupby('Item_Number')['Confidence_Percentage'].idxmax(), ['Item_Number', 'Item_Description', 'Predicted_Product_Taxonomy_Node']]\n",
    "\n",
    "# Rename the column for clarity\n",
    "top_predictions.rename(columns={'Predicted_Product_Taxonomy_Node': 'Top_Predicted_Product_Taxonomy_Node'}, inplace=True)\n",
    "\n",
    "# Get the current date\n",
    "current_date = datetime.now().strftime(\"%d-%m-%Y\")\n",
    "\n",
    "# Define the paths for saving the files\n",
    "top_predictions_path = f\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Top Prediction File\\\\top_predictions_{current_date}.xlsx\"\n",
    "missing_partial_taxonomy_node_path = f\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Missing_partial_taxonomy_node Files\\\\missing_partial_taxonomy_node_{current_date}.xlsx\"\n",
    "\n",
    "# Write the new DataFrame to an Excel file with the current date appended\n",
    "top_predictions.to_excel(top_predictions_path, index=False)\n",
    "\n",
    "# Save the missing items to a new Excel file with the current date appended\n",
    "if missing_partial_taxonomy_node:\n",
    "    missing_partial_taxonomy_node_df = pd.concat(missing_partial_taxonomy_node, ignore_index=True)\n",
    "    try:\n",
    "        missing_partial_taxonomy_node_df.to_excel(missing_partial_taxonomy_node_path, index=False)\n",
    "        logging.info(f\"Missing partial taxonomy node data saved successfully to {missing_partial_taxonomy_node_path}.\")\n",
    "        print(f\"Missing partial taxonomy node data saved successfully to {missing_partial_taxonomy_node_path}.\")\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Error saving missing partial taxonomy node data to {missing_partial_taxonomy_node_path}: {e}\")\n",
    "        print(f\"Error saving missing partial taxonomy node data to {missing_partial_taxonomy_node_path}: {e}\")\n",
    "\n",
    "print(\"Handling Missing Partial Taxonomy Node and First Word...\")\n",
    "\n",
    "# Read the original input data\n",
    "input_data_file = r'C:\\Users\\u113784\\OneDrive - Trane Technologies\\Documents\\Python Code\\SVM\\SVM-7\\Input File.xlsx'\n",
    "try:\n",
    "    input_df = pd.read_excel(input_data_file, usecols=['Item_Number', 'Item_Description'])\n",
    "    logging.info(\"Input data read successfully.\")\n",
    "    print(f\"Input data read successfully from {input_data_file}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error reading data from {input_data_file}: {e}\")\n",
    "    print(f\"Error reading data from {input_data_file}: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Read the top predictions file\n",
    "try:\n",
    "    top_predictions_df = pd.read_excel(top_predictions_path, usecols=['Item_Number'])\n",
    "    logging.info(\"Top predictions data read successfully.\")\n",
    "    print(f\"Top predictions data read successfully from {top_predictions_path}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error reading top predictions data from {top_predictions_path}: {e}\")\n",
    "    print(f\"Error reading top predictions data from {top_predictions_path}: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Standardize the format of Item_Number in both DataFrames\n",
    "input_df['Item_Number'] = input_df['Item_Number'].astype(str)\n",
    "top_predictions_df['Item_Number'] = top_predictions_df['Item_Number'].astype(str)\n",
    "\n",
    "# Identify items that are in the input data but not in the top predictions\n",
    "missing_items_df = input_df[~input_df['Item_Number'].isin(top_predictions_df['Item_Number'])]\n",
    "\n",
    "# Save the missing items to a new Excel file with the current date appended\n",
    "try:\n",
    "    missing_items_df.to_excel(missing_partial_taxonomy_node_path, index=False)\n",
    "    logging.info(f\"Missing partial taxonomy node data saved successfully to {missing_partial_taxonomy_node_path}.\")\n",
    "    print(f\"Missing partial taxonomy node data saved successfully to {missing_partial_taxonomy_node_path}.\")\n",
    "except Exception as e:\n",
    "    logging.error(f\"Error saving missing partial taxonomy node data to {missing_partial_taxonomy_node_path}: {e}\")\n",
    "    print(f\"Error saving missing partial taxonomy node data to {missing_partial_taxonomy_node_path}: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b8473d4-bcae-4a0b-b214-540a51a5c5c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Code-4 Updating to Excel\n",
    "import pandas as pd\n",
    "from datetime import datetime\n",
    "\n",
    "# Define the paths for the input and output files\n",
    "excel_file_path = r'C:\\Users\\u113784\\OneDrive - Trane Technologies\\Documents\\Python Code\\SVM\\Parts Categorization.xlsx'\n",
    "input_data_file = r'C:\\Users\\u113784\\OneDrive - Trane Technologies\\Documents\\Python Code\\SVM\\SVM-7\\Input File.xlsx'\n",
    "current_date = datetime.now().strftime(\"%d-%m-%Y\")\n",
    "top_predictions_path = f\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Top Prediction File\\\\top_predictions_{current_date}.xlsx\"\n",
    "missing_partial_taxonomy_node_path = f\"C:\\\\Users\\\\u113784\\\\OneDrive - Trane Technologies\\\\Documents\\\\Python Code\\\\SVM\\\\SVM-7\\\\Missing_partial_taxonomy_node Files\\\\missing_partial_taxonomy_node_{current_date}.xlsx\"\n",
    "\n",
    "# Read the existing Excel file\n",
    "try:\n",
    "    df = pd.read_excel(excel_file_path, sheet_name='Sheet1')\n",
    "    print(\"Excel file read successfully.\")\n",
    "except Exception as e:\n",
    "    print(f\"Error reading Excel file: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Determine the next SI.No value\n",
    "next_si_no = df['SI.No'].max() + 1 if not df.empty else 1\n",
    "\n",
    "# Get the current month and date\n",
    "current_month = datetime.now().strftime(\"%B\")\n",
    "\n",
    "# Read the input data file to get the total number of items\n",
    "try:\n",
    "    input_df = pd.read_excel(input_data_file, usecols=['Item_Number', 'Item_Description'])\n",
    "    total_items = len(input_df)\n",
    "    print(\"Input data read successfully for total items count.\")\n",
    "except Exception as e:\n",
    "    print(f\"Error reading input data for total items count: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Read the top predictions file to get the total number of items categorized by python\n",
    "try:\n",
    "    top_predictions_df = pd.read_excel(top_predictions_path)\n",
    "    total_items_categorized_by_python = len(top_predictions_df)\n",
    "    print(\"Top predictions data read successfully for categorized items count.\")\n",
    "except Exception as e:\n",
    "    print(f\"Error reading top predictions data for categorized items count: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Read the missing partial taxonomy node file to get the total number of items not categorized\n",
    "try:\n",
    "    missing_items_df = pd.read_excel(missing_partial_taxonomy_node_path)\n",
    "    not_categorized = len(missing_items_df)\n",
    "    print(\"Missing partial taxonomy node data read successfully for not categorized items count.\")\n",
    "except Exception as e:\n",
    "    print(f\"Error reading missing partial taxonomy node data for not categorized items count: {e}\")\n",
    "    exit()\n",
    "\n",
    "# Calculate the required fields\n",
    "Total_Hours_Saved = total_items_categorized_by_python / (300 / 8)\n",
    "Total_Days_Saved = Total_Hours_Saved / 8\n",
    "\n",
    "# Create a new row with the updated data\n",
    "new_row = {\n",
    "    'SI.No': next_si_no,\n",
    "    'Month': current_month,\n",
    "    'Weeks': '',  # Update this if you have the weeks information\n",
    "    'Jira Number': '',  # Update this if you have the Jira number\n",
    "    'Date': current_date,\n",
    "    'File Name': f\"top_predictions_{current_date}.xlsx, missing_partial_taxonomy_node_{current_date}.xlsx\",\n",
    "    'Total items': total_items,\n",
    "    'Total items categorized by python': total_items_categorized_by_python,\n",
    "    'Not Categorize': not_categorized,\n",
    "    'Total Hours Saved': Total_Hours_Saved,\n",
    "    'Total Days Saved': Total_Days_Saved\n",
    "}\n",
    "\n",
    "# Convert the new row to a DataFrame\n",
    "new_row_df = pd.DataFrame([new_row])\n",
    "\n",
    "# Append the new row to the DataFrame using pd.concat\n",
    "df = pd.concat([df, new_row_df], ignore_index=True)\n",
    "\n",
    "# Save the updated DataFrame back to the Excel file\n",
    "try:\n",
    "    df.to_excel(excel_file_path, sheet_name='Sheet1', index=False)\n",
    "    print(\"Excel file updated successfully.\")\n",
    "except Exception as e:\n",
    "    print(f\"Error saving updated Excel file: {e}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
